workspace = {members = ["abc320", "abc147"],exclude = []}
[package]
name = "atcoder-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
